### ISSUE TITLE
Properly set collection efficiency for each photosensor option

### ISSUE THREAD

**Issue by YujiOkajima** [WCSim/WCSim#49]
In WCSim, the table of collection efficiency is exist in WCSimWCSD.cc, but the function which include the table (WCSimWCSD::ProcessHits) seems not to be used. 
To introduce photodetectors' collection efficiency, It is necessary to modify WCSim code.

**Comment by eosullivan** [comment]
The collection_eff table in WCSimWCSD is different from the collection efficiency that we need to implement for the new HK tube candidates. The collection_eff table is related to how the QE is changed as a function of angle, which would only really matter for us near the edges. That being said, we do need to ensure that we are properly understanding and accounting for the collection efficiency as described by Shoei and so the title to descibe this issue is correct.

**Comment by YujiOkajima** [comment]
This is Implemented in #59 .
Therefore I close this issue.
