### ISSUE TITLE
Incorrect hit timing resolution

### ISSUE THREAD

**Issue by YujiOkajima** [WCSim/WCSim#73]
I'm sorry,

I found the function which I used for hit timing resolution analysis of measured data is different from the function which has been already introduced. It will effect in high charge region.

I will fix it as soon as possible.

**Comment by fdilodov** [comment]
Hi, just to understand this issue a bit better. There is a 10-12% difference between what we should have had and what we actually have in the code. Do we have an idea of how much this going to affect the reliability of our results using the SK framework? For the HK tank production I think we can from now work in using the right code (ie fixing WCSim and tuning fiTQun) so the problem is just for SK. I presume that the resolutions we will get will not be correct, but the actual relative comparisons between the different options may still be OK? Can we discuss it at tomorrow's sw meeting?

**Comment by YujiOkajima** [comment]
In low energy study, it may not affect so much, however when the charge of PMT > 23.96 p.e. , the timing resolution becomes worse.
I'm going to describe this problem at the tommorow meeting.

**Comment by fdilodov** [comment]
Thanks.
PS it seems that my comment didn't appear by email but just on the web, 
it is attached below.


On 20/05/15 13:42, YujiOkajima wrote:
>
> In low energy study, it may not affect so much, however when the 
> charge of PMT > 23.96 p.e. , the timing resolution becomes worse.
> I'm going to describe this problem at the tommorow meeting.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WCSim/WCSim/issues/73#issuecomment-103869905>.
>
Hi, just to understand this issue a bit better. There is a 10-12% 
difference between what we should have had and what we actually have in 
the code. Do we have an idea of how much this going to affect the 
reliability of our results using the SK framework? For the HK tank 
production I think we can from now work in using the right code (ie 
fixing WCSim and tuning fiTQun) so the problem is just for SK. I presume 
that the resolutions we will get will not be correct, but the actual 
relative comparisons between the different options may still be OK? Can 
we discuss it at tomorrow's sw meeting?

**Comment by cwwalter** [comment]
Hi Francesca, I got it in email.  You don't get it yourself.  But other people get it.

**Comment by cwwalter** [comment]
BTW, I also want to know how this mistake happened given the checks that were done before.  We waited for many checks to make sure it was correct.  But, it was still wrong.  So, we should understand how it happened so we don't do it again.

**Comment by eosullivan** [comment]
This was corrected in pull request #74
